---
- name: Verificar e instalar Nessus Agent
  hosts: all
  become: yes
  tasks:
    - name: Verificar se o Nessus Agent está instalado
      stat:
        path: /opt/nessus_agent/sbin/nessuscli
      register: nessus_agent

    - name: Instalar Nessus Agent se não estiver presente
      block:
        - name: Informar que o Nessus Agent não está instalado
          debug:
            msg: "Nessus Agent não está instalado. Iniciando a instalação..."

        - name: Instalar Nessus Agent
          shell: |
            curl -H 'X-Key: cc71231b37d195b6afe92a1e5cb0b1cbb4cc3a8b590167429c017c3bbd9c27d3' 'https://sensor.cloud.tenable.com/install/agent?groups=AWS_MGMT_Linux_agent' | bash
          args:
            creates: /opt/nessus_agent/sbin/nessuscli

        - name: Informar que o Nessus Agent foi instalado com sucesso
          debug:
            msg: "Nessus Agent instalado com sucesso!"
      when: nessus_agent.stat.exists == False

    - name: Informar que o Nessus Agent já está instalado
      debug:
        msg: "Nessus Agent já está instalado."
      when: nessus_agent.stat.exists == True
